beyond-sw-camp/be13-fin-Be4After-HOMS-BE

- .gitignore
- homs/build.gradle
- homs/src/main/java/com/beyond/homs/config/SwaggerConfig.java
- homs/src/test/java/com/beyond/homs/HomsApplicationTests.java
gradle 수정, swagger컨픽 추가, profile 을  test로 설정
> Feat: "초기 코드 세팅"

- .idea/.gitignore
- .idea/be13-fin-4team-1.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
> fix: remove git cache

- homs/src/main/java/com/beyond/homs/product/entity/Product.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductCategory.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductFile.java
> Feat: "상품 관련 엔티티 구현"

- homs/src/main/java/com/beyond/homs/HomsApplication.java
- homs/src/main/java/com/beyond/homs/product/entity/Product.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductCategory.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductFile.java
- homs/src/main/java/com/beyond/homs/user/entity/User.java
> fix : add builder pattern and remove unneed annotation

- homs/src/main/java/com/beyond/homs/notice/controller/NoticeController.java
- homs/src/main/java/com/beyond/homs/notice/controller/NoticeControllerImpl.java
- homs/src/main/java/com/beyond/homs/notice/service/NoticeService.java
- homs/src/main/java/com/beyond/homs/notice/service/NoticeServiceImpl.java
> fix: "NoticeRequestDto 이름 변경"

- homs/src/main/java/com/beyond/homs/company/entity/Company.java
- homs/src/main/java/com/beyond/homs/menu/entity/Menu.java
- homs/src/main/java/com/beyond/homs/order/entity/Order.java
- homs/src/main/java/com/beyond/homs/order/entity/Template.java
- homs/src/main/java/com/beyond/homs/settlement/data/SettleStatusEnum.java
- homs/src/main/java/com/beyond/homs/settlement/entity/Settlement.java
- homs/src/main/java/com/beyond/homs/user/entity/LoginAttemptHistory.java
- homs/src/main/java/com/beyond/homs/user/entity/PasswordHistory.java
- homs/src/main/java/com/beyond/homs/user/entity/User.java
메뉴, 정산, 발주템플릿 엔티티 구현 및 이전 엔티티 다수 수정
> Feat: "엔티티 초안 구현"

- homs/src/main/java/com/beyond/homs/settlement/entity/Settlement.java
커밋 컨벤션 예시 설명을 위한 import문 제거(테스트 커밋)
> Fix: "정산 엔티티 수정"

- .gitignore
> Fix : ".gitignore 수정"

- homs/src/main/java/com/beyond/homs/product/controller/ProductCategoryController.java
- homs/src/main/java/com/beyond/homs/product/controller/ProductCategoryControllerImpl.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryListDto.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryRequestDto.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryResponseDto.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductCategory.java
- homs/src/main/java/com/beyond/homs/product/repository/ProductCategoryRepository.java
- homs/src/main/java/com/beyond/homs/product/service/ProductCategoryService.java
- homs/src/main/java/com/beyond/homs/product/service/ProductCategoryServiceImpl.java
> Feat: "상품 분류 카테고리 CRUD 기능 구현"

- homs/src/main/java/com/beyond/homs/order/entity/Order.java
- homs/src/main/java/com/beyond/homs/order/service/OrderServiceImpl.java
> Fix: "발주요청목록 CRUD 구현"

- homs/src/main/java/com/beyond/homs/order/controller/OrderController.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderControllerImpl.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderItemController.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderItemControllerImpl.java
- homs/src/main/java/com/beyond/homs/order/dto/OrderItemRequestDto.java
- homs/src/main/java/com/beyond/homs/order/dto/OrderItemResponseDto.java
- homs/src/main/java/com/beyond/homs/order/entity/OrderItem.java
- homs/src/main/java/com/beyond/homs/order/entity/OrderItemId.java
- homs/src/main/java/com/beyond/homs/order/repository/OrderItemRepository.java
- homs/src/main/java/com/beyond/homs/order/service/OrderItemService.java
- homs/src/main/java/com/beyond/homs/order/service/OrderItemServiceImpl.java
- homs/src/main/java/com/beyond/homs/order/service/OrderServiceImpl.java
- homs/src/main/java/com/beyond/homs/wms/entity/InventoryId.java
주문 상품 조회 등 구현 및 오더 엔티티 수정, serialVersionUID 통일
> Feat: "발주 상품 CRUD 구현"

- homs/src/main/java/com/beyond/homs/auth/jwt/JwtAuthFilter.java
- homs/src/main/java/com/beyond/homs/config/SecurityConfig.java
SecurityConfig 수정 및 JWT 필터에서 인증 필요 없는 부분 URI 제외처리
> Fix: "로그인 관련 수정"

- homs/src/main/java/com/beyond/homs/menu/controller/MenuController.java
- homs/src/main/java/com/beyond/homs/menu/controller/MenuControllerImpl.java
- homs/src/main/java/com/beyond/homs/menu/dto/MenuListDto.java
- homs/src/main/java/com/beyond/homs/menu/dto/MenuRequestDto.java
- homs/src/main/java/com/beyond/homs/menu/dto/MenuResponseDto.java
- homs/src/main/java/com/beyond/homs/menu/entity/Menu.java
- homs/src/main/java/com/beyond/homs/menu/repository/MenuRepository.java
- homs/src/main/java/com/beyond/homs/menu/service/MenuService.java
- homs/src/main/java/com/beyond/homs/menu/service/MenuServiceImpl.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryListDto.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryRequestDto.java
- homs/src/main/java/com/beyond/homs/product/entity/ProductCategory.java
- homs/src/main/java/com/beyond/homs/product/service/ProductCategoryServiceImpl.java
메뉴 CRUD 기능 구현 및 상품 분류 카테고리 active 컬럼 삭제
> Feat: "메뉴 CRUD 기능 구현"

- homs/appspec.yaml
> feat: add app spec file

- homs/src/main/java/com/beyond/homs/company/controller/CompanyControllerImpl.java
- homs/src/main/java/com/beyond/homs/company/dto/CompanyDto.java
- homs/src/main/java/com/beyond/homs/config/SecurityConfig.java
> Fix: "거래처 등록 관련 수정"

- homs/src/main/java/com/beyond/homs/company/service/CompanyServiceImpl.java
- homs/src/main/java/com/beyond/homs/user/dto/UpdateUserDto.java
- homs/src/main/java/com/beyond/homs/user/service/UserAdminServiceImpl.java
- homs/src/main/java/com/beyond/homs/user/service/UserServiceImpl.java
- password update
- add transactional annotation
> fix: add password update and transactional annotation

- homs/src/main/java/com/beyond/homs/user/dto/UserResponseDto.java
UserResponseDto에서 기존 ID값으로 가져오는 방식에서 원활한 프론트 개발을 위해 Name을 직접 가져오는 방식으로 변경
> Fix: "유저dto수정"

- homs/src/main/java/com/beyond/homs/chat/repository/ChatRoomRepository.java
- homs/src/main/java/com/beyond/homs/chat/service/ChatService.java
> Fix: "채팅 JPA레포 수정"

- homs/src/main/java/com/beyond/homs/settlement/controller/SettlementController.java
- homs/src/main/java/com/beyond/homs/settlement/controller/SettlementControllerImpl.java
- homs/src/main/java/com/beyond/homs/settlement/dto/SettlementRequestDto.java
- homs/src/main/java/com/beyond/homs/settlement/dto/SettlementResponseDto.java
- homs/src/main/java/com/beyond/homs/settlement/entity/Settlement.java
- homs/src/main/java/com/beyond/homs/settlement/service/SettlementService.java
- homs/src/main/java/com/beyond/homs/settlement/service/SettlementServiceImpl.java
> Feat: "정산 관리 POST API 추가"

- homs/src/main/java/com/beyond/homs/menu/controller/MenuControllerImpl.java
- homs/src/main/java/com/beyond/homs/menu/service/MenuServiceImpl.java
- homs/src/main/java/com/beyond/homs/wms/controller/DeliveryAddController.java
- homs/src/main/java/com/beyond/homs/wms/controller/DeliveryAddControllerImpl.java
- homs/src/main/java/com/beyond/homs/wms/dto/DeliveryAddRequestDto.java
- homs/src/main/java/com/beyond/homs/wms/dto/DeliveryAddResponseDto.java
- homs/src/main/java/com/beyond/homs/wms/entity/DeliveryAddress.java
- homs/src/main/java/com/beyond/homs/wms/repository/DeliveryAddRepository.java
- homs/src/main/java/com/beyond/homs/wms/service/DeliveryAddService.java
- homs/src/main/java/com/beyond/homs/wms/service/DeliveryAddServiceImpl.java
> Feat: "Delivery Address 추가"

- homs/src/main/java/com/beyond/homs/wms/dto/DeliveryAddResponseDto.java
- homs/src/main/java/com/beyond/homs/wms/service/DeliveryAddServiceImpl.java
> Feat "배송지 DTO 추가"

- homs/src/main/java/com/beyond/homs/auth/handler/AccessDeniedHandlerImpl.java
- homs/src/main/java/com/beyond/homs/auth/handler/AuthenticationEntryPointImpl.java
- homs/src/main/java/com/beyond/homs/auth/jwt/JwtAuthFilter.java
- homs/src/main/java/com/beyond/homs/common/exception/handler/GlobalExceptionHandler.java
- homs/src/main/java/com/beyond/homs/common/filter/LogFilter.java
- homs/src/main/java/com/beyond/homs/config/FilterConfig.java
- homs/src/main/java/com/beyond/homs/config/SecurityConfig.java
security exception handling 추가
> fix: set security exception handling

- homs/src/main/java/com/beyond/homs/config/SwaggerConfig.java
> fix: modify swagger description

- homs/src/main/java/com/beyond/homs/common/email/service/EmailServiceImpl.java
- homs/src/main/java/com/beyond/homs/menu/controller/MenuController.java
- homs/src/main/java/com/beyond/homs/menu/controller/MenuControllerImpl.java
- homs/src/main/java/com/beyond/homs/menu/repository/MenuRepository.java
- homs/src/main/java/com/beyond/homs/menu/service/MenuService.java
- homs/src/main/java/com/beyond/homs/menu/service/MenuServiceImpl.java
- 메뉴 불러오는 방식 변경
- 가입 이메일 템플릿 변경
> fix: "메뉴 불러오는 방식 변경"

- homs/src/main/java/com/beyond/homs/order/controller/OrderItemController.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderItemControllerImpl.java
- homs/src/main/java/com/beyond/homs/order/dto/OrderItemResponseDto.java
- homs/src/main/java/com/beyond/homs/order/repository/OrderItemRepository.java
- homs/src/main/java/com/beyond/homs/order/repository/OrderItemRepositoryImpl.java
- homs/src/main/java/com/beyond/homs/order/service/OrderItemService.java
- homs/src/main/java/com/beyond/homs/order/service/OrderItemServiceImpl.java
- homs/src/main/java/com/beyond/homs/product/dto/ProductCategoryMapper.java
부모 카테고리쪽에서 nullable에러가 나서 ProductCategoryMapper null에러처리
> Feat: "주문건별 모든 상품 조회 api 생성"

- homs/src/main/java/com/beyond/homs/common/email/service/EmailServiceImpl.java
> fix: add log sender

- homs/src/main/java/com/beyond/homs/company/repository/CompanyRepository.java
- homs/src/main/java/com/beyond/homs/contract/controller/ContractController.java
- homs/src/main/java/com/beyond/homs/contract/controller/ContractControllerImpl.java
- homs/src/main/java/com/beyond/homs/contract/dto/ContractDataDto.java
- homs/src/main/java/com/beyond/homs/contract/dto/ContractRequestDto.java
- homs/src/main/java/com/beyond/homs/contract/service/ContractService.java
- homs/src/main/java/com/beyond/homs/contract/service/ContractServiceImpl.java
- homs/src/main/java/com/beyond/homs/product/repository/ProductRepository.java
- 계약 생성할때 id값을 받도록 수정
- 계약 상세에 카테고리를 올바르게 수정
- 프론트에서 값을 시각적으로 보여주기 위해 dto와 /data 추가
> fix: "계약 등록 수정"

- homs/src/main/java/com/beyond/homs/order/dto/ClaimListResponseDto.java
- homs/src/main/java/com/beyond/homs/order/repository/OrderRepositoryImpl.java
> Feat: "클래임 상태 추가"

- homs/src/main/java/com/beyond/homs/common/exception/handler/GlobalExceptionHandler.java
> fix: remove discord message send

- homs/src/main/java/com/beyond/homs/contract/service/ContractServiceImpl.java
- homs/src/main/java/com/beyond/homs/order/service/ClaimServiceImpl.java
- homs/src/main/java/com/beyond/homs/order/service/OrderItemServiceImpl.java
- homs/src/main/java/com/beyond/homs/order/service/OrderServiceImpl.java
> fix: "빈 검색결과 반환"

- homs/src/main/java/com/beyond/homs/common/email/controller/EmailControllerImpl.java
- homs/src/main/java/com/beyond/homs/common/excel/controller/ExcelControllerImpl.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderController.java
- homs/src/main/java/com/beyond/homs/order/controller/OrderControllerImpl.java
- homs/src/main/java/com/beyond/homs/order/repository/OrderItemRepository.java
- homs/src/main/java/com/beyond/homs/order/service/OrderService.java
- homs/src/main/java/com/beyond/homs/order/service/OrderServiceImpl.java
- homs/src/main/java/com/beyond/homs/settlement/controller/SettlementController.java
- homs/src/main/java/com/beyond/homs/settlement/controller/SettlementControllerImpl.java
- homs/src/main/java/com/beyond/homs/settlement/dto/SettlementRequestDto.java
- homs/src/main/java/com/beyond/homs/settlement/service/SettlementService.java
- homs/src/main/java/com/beyond/homs/settlement/service/SettlementServiceImpl.java
- 배송 상태 변경 추가
- 정산 페이징 추가
- 코드 리팩토링
> fix: "배송 상태 변경 추가 / 정산 페이징 추가 / 코드 리팩토링"
